### PR TITLE
Update for Minecraft 1.17

### PR DESCRIPTION
**Pull request by Brokkonaut**
Required for uSkyblock in 1.17

### CODE REVIEW

**Comment by Muspah** [comment]
Could you please PR to uskyblock/bukkit-utils? :)

**Comment by Muspah** [comment]
Sorry, quick reply from the phone. My access to rlf's repositories are limited to being contributor on USB's repo, so I can't merge your PR. We've moved the repositories to a Github org. Please redirect this PR to: https://github.com/uskyblock/bukkit-utils

The new repo contains some early changes to support 1.17, but like always, I'm a mess and haven't continued yet. The USB repository there also contains a 1.17 branche.

Thanks in advance!

**Comment by Brokkonaut** [comment]
Hi, thank you for you response. I have seen that you already fixed the issue in the other repository, so a PR won't be needed.

I did not find that other repository because it is somehow not listed in the forks list of this repo?

**Comment by Muspah** [comment]
Might be possible that I ignored the fork status and just pushed my local repository indeed. Didn't expect to change much in bukkit-utils, I'd prefer to merge classes into USB itself when changes are necessary. Lasted longer then I thought, possibly due to the fact that my availability is always a mess lol.

**Pull request closed without merging**
